% GUI base

function MineSweeper_GUI(fig_width,fig_height)
    global time;
    global RemainingBombs;
    global fig;
    global Smiley;

     fig = figure('Position' , [200,200,fig_width,fig_height],...
    'Resize','off',...
    'MenuBar','none',...
    'Name','MineSweeper',...
    'NumberTitle','off');
    axis tight; 
    ha = axes('units','normalized', ...
            'position',[0 0 1 1]); 
    frame_img = imresize(imread('images/frame.png'),[fig_width,fig_height]);
    uistack(image(frame_img),'bottom');
   

    % Create menus
    gamem = uimenu(fig,'Label','Game');
    beginner_cb = @(s,e)SetBoardDims(fig,'BEGINNER');
    uimenu(gamem,'Label','Beginner', ...
                         'Callback',beginner_cb, ...
                         'Accelerator','1');
    intermediate_cb = @(s,e)SetBoardDims(fig,'INTERMEDIATE');
    uimenu(gamem,'Label','Intermediate', ...
                         'Callback',intermediate_cb, ...
                         'Accelerator','2');
    expert_cb = @(s,e)SetBoardDims(fig,'EXPERT');
    uimenu(gamem,'Label','Expert', ...
                         'Callback',expert_cb, ...
                         'Accelerator','3');

    uimenu(gamem,'Label','Reset Board', ...
                         'Callback',@(s,e)ResetBoard(), ...
                         'Separator','on', ...
                         'Accelerator','R');
    uimenu(gamem,'Label','Close', ...
                         'Callback',@(s,e)Close(this), ...
                         'Separator','on', ...
                         'Accelerator','W');

    hintm = uimenu(fig,'Label','Hint');
    hint = @(s,e)hint_cb();
    uimenu(hintm,'Label','Hint...', ...
                         'Callback',hint, ...
                         'Accelerator','H');
            
                             
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    Smiley_im_orig = imread('images/Happy.png');  % Needs to be true color, i.e. MxNx3

   % im_sized = imresize(im_orig,[35,35]); % size of the button
    im_sized = imresize(Smiley_im_orig, [ fig_height*0.1 , fig_width*0.1]);
    % create a pushbtton ( adapt it to your needs)
    Smiley = uicontrol('style','push',...
         'units','normalized',...
         'position',[0.45,0.86, 0.1, 0.1],...
         'fontsize',14,...
         'callback',@(s,e)ResetBoard());

    set(Smiley,'CData',im_sized);
            

           
    
end