% GUI base
function MineSweeper_GUI(fig_width,fig_height)
    fig = figure('Position' , [400,400,fig_width,fig_height],...
    'Resize','off',...
    'MenuBar','none',...
    'Name','MineSweeper',...
    'NumberTitle','off');
    
    
end

